version: "3.7"
services:
  hey-frontend:
    container_name: hey-frontend
    build:
      context: ./hey-frontend
      dockerfile: Dockerfile
    volumes:
      - "./hey-frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  redis:
    container_name: hey-redis
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - hey-redis-data:/data
    networks:
      - backend-network

  hey-backend:
    container_name: hey-backend
    build:
      context: ./hey-backend
      dockerfile: Dockerfile
    volumes:
      - "hey-backend-log:/app/log"
    networks:
      - backend-network
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - env=production
      - vertx.disableDnsResolver=true

networks:
  backend-network:
    driver: bridge

volumes:
  hey-redis-data:
  hey-backend-log:
