@startuml

actor User

participant AuthServer

database AuthDB

User -> AuthServer: create pin
AuthServer -> AuthServer: authorize user
opt isPermitted is false
    AuthServer --> User: unauthorize
end
AuthServer -> AuthDB: update pin
AuthServer --> User: create pin successfully


@enduml