	
@startuml

actor User

participant PaymentServer
participant AuthServer
database PaymentDB
database Redis

User -> PaymentServer: create transfer
PaymentServer -> AuthServer: authorize user
PaymentServer <-- AuthServer: permission
opt permission is false
    PaymentServer --> User: Unauthorize
end
PaymentServer -> AuthServer: authorize soft token
AuthServer -> Redis: check soft token exist
opt isExist is false 
    AuthServer --> PaymentServer: Expired soft token
    PaymentServer --> User: Bad request
end
PaymentServer <-- AuthServer: amount + userId
opt balance < amount
    PaymentServer --> User: Your balance is not enough
end
PaymentServer -> PaymentDB: create transfer
PaymentServer --> User: transfer successfully
@enduml