// - AUTHENTICATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_START = "LOGIN_START";
export const GET_PROFILE = "GET_PROFILE";

// - LOADING
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// PAYMENT
export const ON_SHOW = "payment.SHOW_TOPUP";
export const SUBMIT_TOPUP = "CHANGE_FONT";
export const ON_SHOW_PIN = "payment.SHOW_PIN";
export const ON_CLOSE_PIN = "payment.CLOSE_PIN";
export const ON_OPEN_ACCEPT_TRANSFER = "payment.ON_OPEN_ACCEPT_TRANSFER";
export const ON_CLOSE_ACCEPT_TRANSFER = "payment.ON_CLOSE_ACCEPT_TRANSFER";
export const ADD_FRIEND_TRANSFER_POPUP = "payment.ADD_FRIEND_TRANSFER_POPUP";
export const ON_UPDATE_BALANCE = "payment.ON_UPDATE_BALANCE";
export const ADD_FRIEND_TO_SESSION = "payment.ADD_FRIEND_TO_SESSION";
export const FETCH_TRANSFER_STATEMENT = "payment.FETCH_TRANSFER_STATEMENT";

// Lucky Money
export const LUCKY_MONEY_POPUP = "payment.LUCKY_MONEY_POPUP";

// Members
export const CHANGE_STATE_MEMBERS_MODAL = "chat.CHANGE_STATE_MEMBERS_MODAL";
export const FETCH_MEMBERS = "chat.FETCH_MEMBER";

//Modal
export const CHANGE_STATE_DRAWER_PROFILE = "modal.CHANGE_STATE_DRAWER_PROFILE";
export const VISIBLE_CHANGE_PROFILE_MODAL =
  "modal.VISIBLE_CHANGE_PROFILE_MODAL";
export const VISIBLE_CHANGE_PASSWORD_MODAL =
  "modal.VISIBLE_CHANGE_PASSWORD_MODAL";
export const VISIBLE_CHANGE_PIN_MODAL = "modal.VISIBLE_CHANGE_PIN_MODAL";
