	
@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as users #Gainsboro{
    *id: number <<generated>>
    --
    username: varchar
    email: varchar
    password: varchar
    full_name: varchar
    pin: varchar
    avatar: varchar
    mini_avatar: varchar
}


entity "systems" #Gainsboro{
    *id: number <<generated>>
    --
    system_name: varchar
    system_key: varchar
}


entity "wallets" as wallets #Aqua{
    *id: number <<generated>>
    --
    balance: number    
    owner_id: number
    ref_from: varchar
    
}

entity "transfer_statements" as transfer_statements #Aqua {
    *id: number <<generated>>
    --
    transfer_code: varchar
    source_id: number <<FK>>
    target_id: number <<FK>>
    amount: number
    created_at: timestamp
    status: number
    transfer_fee: number
    description: string
    transfer_type: varchar
}

entity "lucky_moneys" as lucky_moneys #Yellow{
    *id: number  <<generated>>
    --
    user_id: number <<FK>>
    system_wallet_id: number <<FK>>
    session_chat_id: varchar
    amount: number
    rest_money: number
    rest_bag: number
    number_bag: number
    type: varchar
    wish_message: string
    created_at: timestamp
    expired_at: timestamp
}

entity "received_lucky_moneys" as received_luckey_moneys #Yellow{
    *id: number <<generated>>
    --
    lucky_money_id: number <<FK>>
    receiver_id: number <<FK>>
    amount: number
    created_at: timestamp
}

wallets ||.up.o{ transfer_statements
wallets ||.up.o{ transfer_statements

wallets ||.up.o{ lucky_moneys
wallets ||.up.o{ lucky_moneys

wallets ||.up.o{ received_luckey_moneys

users ||.left.|| wallets

systems ||..o{ wallets


lucky_moneys ||.right.o{ received_luckey_moneys


@enduml