@startuml
skinparam linetype ortho

package "controller" #aqua {
    [Payment Controller]
}

package "entity" #aqua {
    [User]
    [Wallet]
    [System Wallet]
    [Transfer Statement]
    [System]
}


package "service" #aqua{
    [Payment Service]
}

package "repository" #aqua{
    [Transfer Statements Repository]
    [System Users Repository]

}


database "mysql" #orange




@enduml
