@startuml

skinparam linetype ortho


database "MySQL" #Orange
database "Redis" #Orange



[hey-app] --> [hey-chat]
[hey-app] --> [hey-payment]
[hey-app] --> [hey-auth]
[hey-payment]->[hey-auth]
[hey-chat] -left-> [hey-auth]
[hey-auth] --> MySQL
[hey-payment] --> MySQL
[hey-chat] --> Redis

@enduml

